// Каталог, розширений на основі реального інвентарю (Metro-закупівля 17.08.2026).
// 131 позиція: 16 стартових + 115 із живого чеку/комори. Це не 1500-2500 позицій із
// фінальної версії roadmap — це реальні продукти одного домогосподарства, з брендовими
// аліасами так, як вони зустрічаються в чеках. allergen_groups — перший прохід,
// потребує окремої перевірки перед тим, як покладатись на них для реальних алергій
// (див. 04-roadmap.html, розділ «Паралельно» — правова рамка для алергій).

export interface CatalogItem {
  key: string;
  name: string;                  // канонічна назва для людини
  aliases: string[];             // як зустрічається в чеках і мовленні
  categories: string[];          // ієрархія від конкретного до загального
  allergen_groups: string[];     // «молюски», «горіхи», «глютен», «молочне» ...
  zone_default: 'dry' | 'fridge' | 'freezer' | 'fresh' | 'spices' | 'drinks';
  unit_weight?: number;
  density?: number;
  nutrition?: { kcal: number; p: number; f: number; c: number };
}

export const CATALOG: CatalogItem[] = [
  {
    key: 'mussel_meat',
    name: 'Мʼясо мідій',
    aliases: ['мідії', 'мідії варені', 'мʼясо мідій', 'karolina', 'karolina мʼясо мідій', 'мидии', 'mussel meat'],
    categories: ['мідії', 'молюски', 'морепродукти', 'тваринне'],
    allergen_groups: ['молюски', 'морепродукти'],
    zone_default: 'freezer',
    nutrition: { kcal: 172, p: 24, f: 4, c: 7 },
  },
  {
    key: 'salami_milano_pork',
    name: 'Ковбаса Міланська',
    aliases: ['ковбаса міланська', 'міланська', 'salami milano', 'salame milano', 'мілано'],
    categories: ['ковбаса', 'сирокопчене', 'свинина', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'fridge',
    nutrition: { kcal: 407, p: 22, f: 34, c: 1 },
  },
  {
    key: 'cilantro_fresh',
    name: 'Кінза свіжа',
    aliases: ['кінза', 'кінзу', 'кінзи', 'кінзою', 'коріандр свіжий', 'coriander', 'cilantro'],
    categories: ['зелень', 'трави', 'свіже'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'cambozola_cheese',
    name: 'Камбоцола 70%',
    aliases: ['камбоцола', 'cambozola', 'камбоц', 'сир камбоц'],
    categories: ['сир', 'блакитний сир', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 427, p: 15, f: 41, c: 1 },
  },
  {
    key: 'mozzarella_pizza',
    name: 'Моцарела для піци',
    aliases: ['моцарела', 'mozzarella', 'моцарелла'],
    categories: ['сир', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 280, p: 22, f: 22, c: 2 },
  },
  {
    key: 'parmesan',
    name: 'Пармезан',
    aliases: ['пармезан', 'parmigiano', 'parmigiano reggiano', 'grana padano'],
    categories: ['сир', 'твердий сир', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 392, p: 36, f: 26, c: 3 },
  },
  {
    key: 'pomodori_pelati',
    name: 'Помідори пелаті',
    aliases: ['пелаті', 'pomodori pelati', 'томати очищені', 'помідори в соку'],
    categories: ['томати', 'овочі', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 22, p: 1, f: 0, c: 4 },
  },
  {
    key: 'spaghetti_no5',
    name: 'Спагеті №5',
    aliases: ['спагеті', 'спагетті', 'spaghetti', 'паста спагеті', 'паста №5'],
    categories: ['паста', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 358, p: 12, f: 2, c: 71 },
  },
  {
    key: 'olive_oil_evoo',
    name: 'Оливкова олія екстра',
    aliases: ['оливкова олія', 'olive oil', 'evoo', 'олія оливкова'],
    categories: ['олія', 'жири'],
    allergen_groups: [],
    zone_default: 'spices',
    density: 0.91,
    nutrition: { kcal: 884, p: 0, f: 100, c: 0 },
  },
  {
    key: 'garlic',
    name: 'Часник',
    aliases: ['часник', 'часнику', 'часником', 'garlic'],
    categories: ['цибулеві', 'овочі', 'свіже'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'onion_yellow',
    name: 'Цибуля ріпчаста',
    aliases: ['цибуля', 'цибулю', 'цибуля жовта', 'ріпчаста', 'onion'],
    categories: ['цибулеві', 'овочі', 'свіже'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'ground_beef_pork',
    name: 'Яловично-свинячий фарш',
    aliases: ['фарш', 'яловично-свинячий фарш', 'фарш яловичо-свинячий', 'фарш м’ясний'],
    categories: ['фарш', 'свинина', 'яловичина', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'fridge',
    nutrition: { kcal: 250, p: 17, f: 20, c: 0 },
  },
  {
    key: 'chicken_whole',
    name: 'Курка ціла',
    aliases: ['курка', 'курки', 'курча', 'chicken', 'куряче тушка'],
    categories: ['курка', 'птиця', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'fridge',
    nutrition: { kcal: 239, p: 27, f: 14, c: 0 },
  },
  {
    key: 'salmon_fresh',
    name: 'Лосось охолоджений',
    aliases: ['лосось', 'лосося', 'salmon', 'сьомга'],
    categories: ['лосось', 'риба', 'тваринне'],
    allergen_groups: ['риба'],
    zone_default: 'fridge',
    nutrition: { kcal: 206, p: 22, f: 13, c: 0 },
  },
  {
    key: 'peanut',
    name: 'Арахіс',
    aliases: ['арахіс', 'арахісу', 'peanut', 'земляний горіх'],
    categories: ['арахіс', 'бобові'],
    allergen_groups: ['арахіс'],
    zone_default: 'dry',
    nutrition: { kcal: 567, p: 26, f: 49, c: 16 },
  },
  {
    key: 'milk_cow_25',
    name: 'Молоко коровʼяче 2.5%',
    aliases: ['молоко', 'молоко 2.5%', 'молоко пастеризоване', 'milk', 'молоко корівʼяче'],
    categories: ['молоко', 'молочне'],
    allergen_groups: ['молочне', 'лактоза'],
    zone_default: 'fridge',
    density: 1.03,
    nutrition: { kcal: 50, p: 3.3, f: 2.5, c: 4.8 },
  },
  {
    key: 'white_beans_canned',
    name: 'Квасоля біла консервована',
    aliases: ['квасоля біла консервована', 'квасоля стерилізована', 'welldar квасоля', 'білі боби консервовані'],
    categories: ['квасоля', 'бобові', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 127, p: 8.7, f: 0.5, c: 21 },
  },
  {
    key: 'green_peas_canned',
    name: 'Горошок зелений консервований',
    aliases: ['горошок зелений', 'зелений горошок', 'верес горошок', 'canned peas'],
    categories: ['горошок', 'бобові', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 55, p: 5, f: 0.5, c: 8 },
  },
  {
    key: 'corn_canned',
    name: 'Кукурудза консервована солодка',
    aliases: ['кукурудза консервована', 'кукурудза солодка', 'canned corn'],
    categories: ['кукурудза', 'овочі', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 76, p: 2.9, f: 1.2, c: 15 },
  },
  {
    key: 'cherry_tomatoes_canned',
    name: 'Томати чері консервовані',
    aliases: ['томати чері ж/б', 'mc томати чері', 'cherry tomatoes canned'],
    categories: ['томати', 'овочі', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 22, p: 1, f: 0, c: 4 },
  },
  {
    key: 'tomatoes_roasted_olives',
    name: 'Помідори запечені з оливками',
    aliases: ['pomodori al forno', 'sacla pomodori al forno', 'помідори запечені'],
    categories: ['томати', 'овочі', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
  },
  {
    key: 'beef_stew_canned',
    name: 'Яловичина тушкована',
    aliases: ['тушонка яловича', 'яловичина тушкована', 'canned beef'],
    categories: ['яловичина', 'мʼясо', 'консерви', 'тваринне'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 220, p: 15, f: 17, c: 0 },
  },
  {
    key: 'tuna_canned',
    name: 'Тунець консервований',
    aliases: ['rio mare тунець', 'тунець консервований', 'canned tuna'],
    categories: ['тунець', 'риба', 'консерви', 'тваринне'],
    allergen_groups: ['риба'],
    zone_default: 'dry',
    nutrition: { kcal: 116, p: 26, f: 1, c: 0 },
  },
  {
    key: 'smoked_salmon_oil',
    name: 'Лосось копчений в олії',
    aliases: ['metro chef лосось копчений', 'лосось копчений в олії'],
    categories: ['лосось', 'риба', 'консерви', 'тваринне'],
    allergen_groups: ['риба'],
    zone_default: 'dry',
    nutrition: { kcal: 190, p: 20, f: 12, c: 0 },
  },
  {
    key: 'herring_salted_fillet',
    name: 'Філе оселедця солоне',
    aliases: ['оселедець солоний', 'філе оселедця', 'metro chef оселедець'],
    categories: ['оселедець', 'риба', 'тваринне'],
    allergen_groups: ['риба'],
    zone_default: 'fridge',
    nutrition: { kcal: 218, p: 18, f: 15, c: 0 },
  },
  {
    key: 'capers_vinegar',
    name: 'Каперси в оцті',
    aliases: ['serpis каперси', 'каперси'],
    categories: ['каперси', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
  },
  {
    key: 'kimchi',
    name: 'Кімчі',
    aliases: ['sempio кімчі', 'kimchi'],
    categories: ['кімчі', 'ферментоване', 'овочі'],
    allergen_groups: ['риба'],
    zone_default: 'fridge',
  },
  {
    key: 'anchovies_oil',
    name: 'Анчоуси в олії',
    aliases: ['rizzoli анчоуси', 'anchovies'],
    categories: ['анчоуси', 'риба', 'консерви'],
    allergen_groups: ['риба'],
    zone_default: 'dry',
    nutrition: { kcal: 210, p: 29, f: 10, c: 0 },
  },
  {
    key: 'olives_green',
    name: 'Оливки зелені',
    aliases: ['оливки зелені', 'chupadedos', 'familia iruela зелені', 'metro chef зелені мариновані'],
    categories: ['оливки', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 145, p: 1, f: 15, c: 4 },
  },
  {
    key: 'olives_black_kalamata',
    name: 'Оливки чорні каламата',
    aliases: ['каламата', 'kalamata', 'оливки каламата', 'mc каламата'],
    categories: ['оливки', 'консерви'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 115, p: 1, f: 11, c: 6 },
  },
  {
    key: 'lentils_green',
    name: 'Сочевиця зелена',
    aliases: ['сочевиця', 'сочевиця зелена', 'lentils'],
    categories: ['сочевиця', 'бобові'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 116, p: 9, f: 0.4, c: 20 },
  },
  {
    key: 'white_beans_dry',
    name: 'Квасоля біла суха',
    aliases: ['аромікс квасоля', 'квасоля суха', 'dry white beans'],
    categories: ['квасоля', 'бобові'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 333, p: 23, f: 1, c: 60 },
  },
  {
    key: 'pearl_barley',
    name: 'Перлова крупа',
    aliases: ['сквирянка перлова крупа', 'перлова крупа', 'pearl barley'],
    categories: ['крупа', 'зернові'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 352, p: 9.9, f: 1.1, c: 77 },
  },
  {
    key: 'pasta_bucatini',
    name: 'Букатіні',
    aliases: ['barilla bucatini', 'bucatini n.9', 'букатіні'],
    categories: ['паста', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 358, p: 12, f: 1.5, c: 72 },
  },
  {
    key: 'pasta_farfalle',
    name: 'Фарфалле',
    aliases: ['barilla фарфалле', 'farfalle n.65', 'фарфалле'],
    categories: ['паста', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 358, p: 12, f: 1.5, c: 72 },
  },
  {
    key: 'pasta_risoni',
    name: 'Рісоні',
    aliases: ['barilla рісоні', 'risoni', 'різоні'],
    categories: ['паста', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 358, p: 12, f: 1.5, c: 72 },
  },
  {
    key: 'pasta_fettuccine_egg',
    name: 'Фетучіне яєчні',
    aliases: ['barilla фетучіне', 'fettuccine', 'яєчна паста'],
    categories: ['паста', 'борошняне', 'яйця'],
    allergen_groups: ['глютен', 'яйця'],
    zone_default: 'dry',
    nutrition: { kcal: 371, p: 14, f: 3.5, c: 71 },
  },
  {
    key: 'udon_noodles',
    name: 'Локшина удон',
    aliases: ['flower land udon', 'удон'],
    categories: ['локшина', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
  },
  {
    key: 'noodles_wheat_asian',
    name: 'Локшина пшенична (класична/бан мьян/шансі даосяо)',
    aliases: ['jml локшина', 'ban mian', 'shanxi daoxiao', 'локшина класична'],
    categories: ['локшина', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
  },
  {
    key: 'tteok_cheese_cup',
    name: 'Токпоккі сирна чашка (Rapokki)',
    aliases: ['yopokki cheese cup rapokki', 'рапоккі'],
    categories: ['токпоккі', 'готове'],
    allergen_groups: ['глютен', 'молочне'],
    zone_default: 'dry',
  },
  {
    key: 'muesli',
    name: 'Мюслі',
    aliases: ['doctor benner мюслі', 'cherry crunchy', 'мюслі'],
    categories: ['сніданок', 'зернові'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 380, p: 9, f: 7, c: 70 },
  },
  {
    key: 'cocoa_balls_cereal',
    name: 'Кульки з какао',
    aliases: ['metro chef кульки з какао', 'шоколадні кульки'],
    categories: ['сніданок', 'зернові'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 390, p: 6, f: 5, c: 80 },
  },
  {
    key: 'oat_flakes',
    name: 'Вівсяні пластівці цільнозернові',
    aliases: ['аха вівсянка', 'вівсяні пластівці', 'oat flakes'],
    categories: ['вівсянка', 'зернові'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 389, p: 13, f: 7, c: 66 },
  },
  {
    key: 'granola_tropical',
    name: 'Гранола тропічні фрукти',
    aliases: ['аха гранола', 'granola'],
    categories: ['сніданок', 'зернові'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 450, p: 8, f: 18, c: 64 },
  },
  {
    key: 'fruit_jelly',
    name: 'Желе фруктове',
    aliases: ['мрія желе', 'желе апельсин вишня лісові ягоди'],
    categories: ['желе', 'солодке'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 70, p: 1, f: 0, c: 17 },
  },
  {
    key: 'milk_chocolate_bar',
    name: 'Шоколад молочний',
    aliases: ['rioba шоколад', 'шоколад сіль кукурудза'],
    categories: ['шоколад', 'солодке'],
    allergen_groups: ['молочне'],
    zone_default: 'dry',
    nutrition: { kcal: 534, p: 7, f: 31, c: 57 },
  },
  {
    key: 'honey',
    name: 'Мед',
    aliases: ['honey way мед', 'мед різнотрав\'я'],
    categories: ['мед', 'солодке'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 304, p: 0.3, f: 0, c: 82 },
  },
  {
    key: 'jam_mixed',
    name: 'Джем',
    aliases: ['джем інжирний helios', 'джем апельсиновий zuegg', 'джем журавлина-лимон', 'варення'],
    categories: ['джем', 'солодке'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 250, p: 0.3, f: 0, c: 62 },
  },
  {
    key: 'condensed_milk',
    name: 'Згущене молоко',
    aliases: ['згущенка', 'condensed milk'],
    categories: ['молочне', 'солодке'],
    allergen_groups: ['молочне'],
    zone_default: 'dry',
    nutrition: { kcal: 321, p: 7.5, f: 8.5, c: 56 },
  },
  {
    key: 'brown_sugar',
    name: 'Цукор тростинний',
    aliases: ['mc цукор тростинний', 'коричневий цукор', 'cane sugar'],
    categories: ['цукор', 'солодке'],
    allergen_groups: [],
    zone_default: 'dry',
    nutrition: { kcal: 398, p: 0, f: 0, c: 98 },
  },
  {
    key: 'pea_mushroom_soup_mix',
    name: 'Крем-суп гороховий/грибний сухий',
    aliases: ['street soup гороховий', 'street soup грибний', 'сухий суп'],
    categories: ['суп', 'готове'],
    allergen_groups: [],
    zone_default: 'dry',
  },
  {
    key: 'rice_paper',
    name: 'Рисовий папір',
    aliases: ['golden calf рисовий папір', 'rice paper'],
    categories: ['рисовий папір', 'азійська кухня'],
    allergen_groups: [],
    zone_default: 'dry',
  },
  {
    key: 'tteokbokki_rose',
    name: 'Токпоккі роузе',
    aliases: ['hipokki tteokbokki rose', 'токпоккі'],
    categories: ['токпоккі', 'готове'],
    allergen_groups: ['глютен', 'молочне'],
    zone_default: 'dry',
  },
  {
    key: 'potato',
    name: 'Картопля',
    aliases: ['картопля', 'potato'],
    categories: ['картопля', 'овочі'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'apple_green',
    name: 'Яблука зелені',
    aliases: ['яблука зелені', 'green apple'],
    categories: ['яблука', 'фрукти'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'grapefruit',
    name: 'Грейпфрут',
    aliases: ['грейпфрут', 'grapefruit'],
    categories: ['цитрусові', 'фрукти'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'redcurrant',
    name: 'Порічки червоні',
    aliases: ['порічки', 'redcurrant'],
    categories: ['ягоди', 'фрукти'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'pickled_cucumbers',
    name: 'Огірки солоні',
    aliases: ['солоні огірки', 'мариновані огірки', 'pickled cucumbers'],
    categories: ['огірки', 'консерви', 'овочі'],
    allergen_groups: [],
    zone_default: 'fridge',
  },
  {
    key: 'orange',
    name: 'Апельсин',
    aliases: ['апельсин', 'orange'],
    categories: ['цитрусові', 'фрукти'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'tomato_yellow',
    name: 'Томат жовтий',
    aliases: ['томат жовтий', 'жовтий помідор', 'yellow tomato'],
    categories: ['томати', 'овочі', 'свіже'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'salad_baby_mix',
    name: 'Салат бебі мікс',
    aliases: ['mc салат бебі мікс', 'baby salad mix', 'мікс салату'],
    categories: ['салат', 'зелень', 'свіже'],
    allergen_groups: [],
    zone_default: 'fresh',
  },
  {
    key: 'shrimp_vannamei',
    name: 'Креветки vannamei',
    aliases: ['metro chef креветки vannamei', 'креветки 58/66', 'mc креветки 70/90'],
    categories: ['креветки', 'ракоподібні', 'морепродукти', 'тваринне'],
    allergen_groups: ['ракоподібні', 'морепродукти'],
    zone_default: 'freezer',
    nutrition: { kcal: 99, p: 24, f: 0.3, c: 0.2 },
  },
  {
    key: 'seafood_cocktail',
    name: 'Морський коктейль',
    aliases: ['ps морський коктейль', 'seafood cocktail'],
    categories: ['морепродукти', 'тваринне'],
    allergen_groups: ['морепродукти', 'молюски', 'ракоподібні', 'риба'],
    zone_default: 'freezer',
  },
  {
    key: 'tuna_steak',
    name: 'Тунець стейк',
    aliases: ['тунець стейки', 'yapiko стейки тунця', 'tuna steak'],
    categories: ['тунець', 'риба', 'тваринне'],
    allergen_groups: ['риба'],
    zone_default: 'freezer',
    nutrition: { kcal: 144, p: 23, f: 5, c: 0 },
  },
  {
    key: 'salmon_portioned_frozen',
    name: 'Лосось порційний морожений',
    aliases: ['mc лосось порційний', 'frozen salmon portion'],
    categories: ['лосось', 'риба', 'тваринне'],
    allergen_groups: ['риба'],
    zone_default: 'freezer',
    nutrition: { kcal: 206, p: 22, f: 13, c: 0 },
  },
  {
    key: 'smoked_bacon',
    name: 'Сало копчене',
    aliases: ['сало копчене генеральське', 'smoked bacon fat'],
    categories: ['сало', 'свинина', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'freezer',
    nutrition: { kcal: 770, p: 2, f: 83, c: 0 },
  },
  {
    key: 'spinach_frozen',
    name: 'Шпинат морожений порційний',
    aliases: ['fl шпинат порційний', 'frozen spinach'],
    categories: ['шпинат', 'зелень', 'овочі'],
    allergen_groups: [],
    zone_default: 'freezer',
    nutrition: { kcal: 23, p: 2.9, f: 0.4, c: 3.6 },
  },
  {
    key: 'mushrooms_frozen',
    name: 'Гриби білі морожені різані',
    aliases: ['spela білі гриби', 'frozen porcini'],
    categories: ['гриби', 'овочі'],
    allergen_groups: [],
    zone_default: 'freezer',
    nutrition: { kcal: 22, p: 2, f: 0.3, c: 2 },
  },
  {
    key: 'potato_pancakes_frozen',
    name: 'Панкейки картопляні морожені',
    aliases: ['mc панкейки картопляні', 'деруни морожені'],
    categories: ['дерун', 'картопля', 'готове', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'freezer',
  },
  {
    key: 'mexico_mix_veg',
    name: 'Овочева суміш Mexico-Mix',
    aliases: ['metro chef mexico-mix', 'мексиканська суміш'],
    categories: ['овочева суміш', 'овочі'],
    allergen_groups: [],
    zone_default: 'freezer',
  },
  {
    key: 'avocado_halves_frozen',
    name: 'Авокадо половинки морожені',
    aliases: ['авокадо половинки', 'frozen avocado'],
    categories: ['авокадо', 'фрукти', 'свіже'],
    allergen_groups: [],
    zone_default: 'freezer',
    nutrition: { kcal: 160, p: 2, f: 15, c: 9 },
  },
  {
    key: 'herbs_frozen_mix',
    name: 'Зелень морожена (кріп/петрушка/цибуля)',
    aliases: ['заморожена зелень', 'frozen herbs mix'],
    categories: ['зелень', 'трави'],
    allergen_groups: [],
    zone_default: 'freezer',
  },
  {
    key: 'chicken_nuggets',
    name: 'Нагетси курячі',
    aliases: ['нагетси', 'chicken nuggets'],
    categories: ['курка', 'напівфабрикат', 'тваринне'],
    allergen_groups: ['глютен'],
    zone_default: 'freezer',
    nutrition: { kcal: 250, p: 14, f: 15, c: 15 },
  },
  {
    key: 'beef_burger_patties',
    name: 'Котлети бургерні яловичі',
    aliases: ['глобино котлети бургерні', 'beef burger patty'],
    categories: ['яловичина', 'мʼясо', 'тваринне', 'напівфабрикат'],
    allergen_groups: [],
    zone_default: 'freezer',
    nutrition: { kcal: 230, p: 16, f: 18, c: 1 },
  },
  {
    key: 'turkey_patties',
    name: 'Котлети індичі',
    aliases: ['котлети індичі', 'turkey patties'],
    categories: ['індичка', 'мʼясо', 'птиця', 'тваринне', 'напівфабрикат'],
    allergen_groups: [],
    zone_default: 'freezer',
    nutrition: { kcal: 170, p: 18, f: 10, c: 2 },
  },
  {
    key: 'boston_buns',
    name: 'Булочки Boston buns',
    aliases: ['boston buns', 'булочки бостон'],
    categories: ['випічка', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
  },
  {
    key: 'ciabatta_cheese',
    name: 'Чіабата з сиром',
    aliases: ['чіабата з сиром'],
    categories: ['випічка', 'хліб', 'борошняне'],
    allergen_groups: ['глютен', 'молочне'],
    zone_default: 'dry',
  },
  {
    key: 'cream_20',
    name: 'Вершки 20%',
    aliases: ['вершки 20%', 'cream 20%'],
    categories: ['вершки', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 206, p: 2.8, f: 20, c: 3.7 },
  },
  {
    key: 'cream_33',
    name: 'Вершки 33%',
    aliases: ['галичина вершки 33%', 'вершки 33%'],
    categories: ['вершки', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 317, p: 2.5, f: 33, c: 3 },
  },
  {
    key: 'ayran',
    name: 'Айран',
    aliases: ['mc айран', 'ayran'],
    categories: ['кисломолочне', 'молочне', 'напої'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 38, p: 1.5, f: 1.5, c: 4 },
  },
  {
    key: 'yogurt_drinkable',
    name: 'Йогурт питний',
    aliases: ['metro chef йогурт питний полуниця-банан', 'drinkable yogurt'],
    categories: ['йогурт', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 65, p: 2.5, f: 1.5, c: 10 },
  },
  {
    key: 'eggs_chicken',
    name: 'Яйця курячі',
    aliases: ['mc яйця курячі с0', 'яйця', 'eggs'],
    categories: ['яйця', 'тваринне'],
    allergen_groups: ['яйця'],
    zone_default: 'fridge',
    nutrition: { kcal: 143, p: 13, f: 9.5, c: 0.7 },
  },
  {
    key: 'gouda_cheese',
    name: 'Гауда',
    aliases: ['гауда 48%', 'gouda'],
    categories: ['сир', 'твердий сир', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 356, p: 25, f: 27, c: 2 },
  },
  {
    key: 'brie_cheese',
    name: 'Брі',
    aliases: ['брі', 'brie'],
    categories: ['сир', 'мʼякий сир', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 334, p: 21, f: 28, c: 0.5 },
  },
  {
    key: 'camembert_cheese',
    name: 'Камамбер',
    aliases: ['mc камамбер', 'camembert'],
    categories: ['сир', 'мʼякий сир', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 300, p: 20, f: 24, c: 0.5 },
  },
  {
    key: 'shrimp_cheese_spread',
    name: 'Сир з креветками',
    aliases: ['kavli сир з креветками', 'shrimp cheese spread'],
    categories: ['сир', 'молочне', 'морепродукти'],
    allergen_groups: ['молочне', 'ракоподібні'],
    zone_default: 'fridge',
  },
  {
    key: 'prosciutto_crudo',
    name: 'Прошуто крудо',
    aliases: ['прошуто', 'prosciutto crudo'],
    categories: ['шинка', 'свинина', 'сирокопчене', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'fridge',
    nutrition: { kcal: 250, p: 26, f: 16, c: 0 },
  },
  {
    key: 'salami_italian_sliced',
    name: 'Салямі італійське нарізка',
    aliases: ['глобино салямі італійське', 'salami sliced'],
    categories: ['ковбаса', 'сирокопчене', 'свинина', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'fridge',
    nutrition: { kcal: 400, p: 22, f: 34, c: 1 },
  },
  {
    key: 'fuet_sausage',
    name: 'Фует',
    aliases: ['mc фует', 'fuet'],
    categories: ['ковбаса', 'сирокопчене', 'свинина', 'мʼясо', 'тваринне'],
    allergen_groups: [],
    zone_default: 'fridge',
    nutrition: { kcal: 450, p: 24, f: 38, c: 1 },
  },
  {
    key: 'butter',
    name: 'Масло вершкове',
    aliases: ['масло вершкове', 'butter'],
    categories: ['масло', 'молочне'],
    allergen_groups: ['молочне'],
    zone_default: 'fridge',
    nutrition: { kcal: 748, p: 0.8, f: 82.5, c: 0.8 },
  },
  {
    key: 'truffle_oil',
    name: 'Олія трюфельна',
    aliases: ['monini трюфельна', 'truffle oil'],
    categories: ['олія', 'жири'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'basil_oil',
    name: 'Олія базилікова',
    aliases: ['monini базилікова', 'basil oil'],
    categories: ['олія', 'жири'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'lemon_oil',
    name: 'Олія лимонна',
    aliases: ['monini лимонна', 'lemon oil'],
    categories: ['олія', 'жири'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'sunflower_oil',
    name: 'Олія соняшникова',
    aliases: ['олейна', 'sunflower oil'],
    categories: ['олія', 'жири'],
    allergen_groups: [],
    zone_default: 'spices',
    nutrition: { kcal: 884, p: 0, f: 100, c: 0 },
  },
  {
    key: 'balsamic_vinegar',
    name: 'Оцет бальзамічний',
    aliases: ['бальзамік modena igp', 'balsamic vinegar'],
    categories: ['оцет'],
    allergen_groups: [],
    zone_default: 'spices',
    nutrition: { kcal: 88, p: 0.5, f: 0, c: 17 },
  },
  {
    key: 'pesto',
    name: 'Песто',
    aliases: ['fratelli mantova песто', 'pesto'],
    categories: ['соус'],
    allergen_groups: ['молочне', 'горіхи'],
    zone_default: 'spices',
  },
  {
    key: 'garlic_sauce',
    name: 'Соус часниковий',
    aliases: ['торчин часниковий', 'garlic sauce'],
    categories: ['соус'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'tomato_paste',
    name: 'Томатна паста',
    aliases: ['чумак томатна паста', 'tomato paste'],
    categories: ['соус', 'томати'],
    allergen_groups: [],
    zone_default: 'spices',
    nutrition: { kcal: 82, p: 4.3, f: 0.5, c: 19 },
  },
  {
    key: 'mango_chili_sauce',
    name: 'Соус манго-чилі',
    aliases: ['j\'elite манго-чилі', 'mango chili sauce'],
    categories: ['соус'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'sriracha',
    name: 'Шрірача',
    aliases: ['sriracha'],
    categories: ['соус'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'soy_sauce',
    name: 'Соєвий соус',
    aliases: ['yamamori gf соєвий соус', 'bonsai premium соєвий соус', 'peri&peri соєвий соус', 'soy sauce'],
    categories: ['соус', 'соя'],
    allergen_groups: ['соя', 'глютен'],
    zone_default: 'spices',
    nutrition: { kcal: 53, p: 8, f: 0, c: 5 },
  },
  {
    key: 'oregano_dried',
    name: 'Орегано сушене',
    aliases: ['fl орегано', 'dried oregano'],
    categories: ['спеції', 'трави'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'coriander_ground',
    name: 'Коріандр мелений',
    aliases: ['мрія коріандр мелений', 'ground coriander'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'paprika_sweet',
    name: 'Паприка солодка',
    aliases: ['mc паприка солодка', 'sweet paprika'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'lemon_pepper',
    name: 'Перець з лимонним ароматом',
    aliases: ['еко перець з лимонним ароматом', 'lemon pepper'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'mustard',
    name: 'Гірчиця',
    aliases: ['верес гірчиця міцна', 'kühne гірчиця зерниста', 'mustard'],
    categories: ['соус', 'спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'beef_stock_concentrate',
    name: 'Яловичий фонд',
    aliases: ['chef club яловичий фонд', 'beef stock concentrate'],
    categories: ['бульйон', 'спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'vegetable_seasoning_11',
    name: 'Приправа «11 овочів»',
    aliases: ['11 овочів'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'smoked_tomato_seasoning',
    name: 'Спеція «томат копчений»',
    aliases: ['томат копчений'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'caramelized_onion_seasoning',
    name: 'Спеція «цибуля карамелізована»',
    aliases: ['цибуля карамелізована'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'dried_lemon',
    name: 'Лимон сушений',
    aliases: ['лимон сушений'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'caramel_vanilla_spice',
    name: 'Приправа карамель-ваніль',
    aliases: ['kotanyi карамель-ваніль'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'bay_leaf',
    name: 'Лавровий лист',
    aliases: ['лавровий лист', 'bay leaf'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'garlic_dried',
    name: 'Часник сушений',
    aliases: ['часник сушений', 'dried garlic'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'black_pepper',
    name: 'Перець чорний',
    aliases: ['чорний перець', 'black pepper'],
    categories: ['спеції'],
    allergen_groups: [],
    zone_default: 'spices',
  },
  {
    key: 'wine_chenin_blanc',
    name: 'Вино Шенін Блан',
    aliases: ['capeography шенін блан', 'chenin blanc'],
    categories: ['вино', 'алкоголь', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'wine_sauvignon_blanc_nonalcoholic',
    name: 'Совіньйон Блан безалкогольний',
    aliases: ['hans greyl совіньйон блан б/а'],
    categories: ['вино безалкогольне', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'lemonade_double_lemon',
    name: 'Лимонад Double Lemon',
    aliases: ['double dutch double lemon'],
    categories: ['лимонад', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'tonic_skinny',
    name: 'Тонік Skinny Tonic',
    aliases: ['double dutch skinny tonic'],
    categories: ['тонік', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'tonic_cucumber',
    name: 'Тонік огірковий',
    aliases: ['fever tree тонік огірковий'],
    categories: ['тонік', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'pineapple_nectar',
    name: 'Нектар ананасовий',
    aliases: ['sandora нектар ананасовий'],
    categories: ['нектар', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
    nutrition: { kcal: 54, p: 0.3, f: 0, c: 13 },
  },
  {
    key: 'lemon_juice',
    name: 'Сік лимонний',
    aliases: ['sandora сік лимонний', 'lemon juice'],
    categories: ['сік', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'mineral_water',
    name: 'Вода мінеральна',
    aliases: ['borjomi', 'mineral water'],
    categories: ['вода', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'kvass',
    name: 'Квас',
    aliases: ['квас тарас білий', 'kvass'],
    categories: ['квас', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'drip_coffee',
    name: 'Кава дріп-пакети',
    aliases: ['дріп-кава', 'drip coffee'],
    categories: ['кава', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'tea_assorted',
    name: 'Чай',
    aliases: ['rioba чай', 'карпатський чай', 'м\'ятна свіжість чай', 'tea'],
    categories: ['чай', 'напої'],
    allergen_groups: [],
    zone_default: 'drinks',
  },
  {
    key: 'bruschette',
    name: 'Брускети',
    aliases: ['maretti брускети', 'bruschette'],
    categories: ['снеки', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
  },
  {
    key: 'nori_snacks',
    name: 'Норі снеки',
    aliases: ['tao kae noi норі', 'nori snacks'],
    categories: ['снеки', 'водорості'],
    allergen_groups: [],
    zone_default: 'dry',
  },
  {
    key: 'corn_snacks',
    name: 'Кукурудзяні снеки',
    aliases: ['ryabchick снеки'],
    categories: ['снеки', 'кукурудза'],
    allergen_groups: [],
    zone_default: 'dry',
  },
  {
    key: 'chips_cheese',
    name: 'Чипси зі смаком сиру',
    aliases: ['lay\'s чипси сир', 'cheese chips'],
    categories: ['снеки', 'картопля'],
    allergen_groups: ['молочне'],
    zone_default: 'dry',
    nutrition: { kcal: 536, p: 6, f: 34, c: 53 },
  },
  {
    key: 'breadcrumbs',
    name: 'Сухарі панірувальні',
    aliases: ['fine life сухарі панірувальні', 'breadcrumbs'],
    categories: ['панірування', 'борошняне'],
    allergen_groups: ['глютен'],
    zone_default: 'dry',
    nutrition: { kcal: 395, p: 13, f: 5, c: 73 },
  },
];

export const BY_KEY = new Map(CATALOG.map((i) => [i.key, i]));
